version: '3'

services:
   web:
      build: .
      image: my-python-app:v1
      ports:
        - "5000:5000"
      
      volumes:
        - .:/app_py

      environment:
        - FLASK_APP=app.py
        - FLASK_ENV=development
        - FLASK_DEBUG=1
      
      restart: always
    